pwa-builder/pwa-studio

src/extension.ts, src/services/manifest/manifest-service.ts, src/services/validation.ts
better validation for a 512x512 icon, including adding one if needed.
=> Validate icon

src/library/package-utils.ts, src/services/package/package-app.ts
=> Packaging improvements

package.json, src/extension.ts, src/library/local-storage.ts, src/services/manifest/manifest-service.ts, src/services/package/package-view.ts, src/services/service-worker.ts, src/services/validation/validation-view.ts, src/services/web-publish.ts
- store ready checklist in our view container. User can see if they are ready to publish to the web + stores right from within vscode.
- If the user has not yet published their PWA to the web, they will be led to publish with Azure Static Web Apps.
=> Publish viewpanel

src/extension.ts, src/services/manifest/manifest-service.ts, src/services/service-worker.ts, src/services/validation/validation-view.ts, src/services/validation/validation.ts, src/services/web-publish.ts
This PR completes:
https://github.com/pwa-builder/PWABuilder/issues/2367
https://github.com/pwa-builder/PWABuilder/issues/2360
https://github.com/pwa-builder/PWABuilder/issues/2359
https://github.com/pwa-builder/PWABuilder/issues/2358
https://github.com/pwa-builder/PWABuilder/issues/2357
=> Status bar items + upgraded sw and manifest flow + tree view refresh fixes

package-lock.json, package.json, src/extension.ts, src/services/manifest/manifest-content.ts, src/services/manifest/manifest-service.ts, src/services/package/package-android-app.ts, src/services/package/package-app.ts, src/services/validation/validation.ts, tsconfig.json
Fixes this issue https://github.com/pwa-builder/PWABuilder/issues/2370
=> Icons update

src/library/package-utils.ts, src/questions.ts, src/services/package/package-app.ts
Adds support for the iOS platform
=> iOS platform

src/services/service-worker.ts
Fixes https://github.com/pwa-builder/PWABuilder/issues/2413
=> fix(): handleAddingToIndex is only called after the file has been found

package.json, snippets/pwa-windows.js.code-snippets, snippets/pwa-windows.json.code-snippets
Fixes https://github.com/pwa-builder/PWABuilder/issues/2363
=> feat(): migrate snippets to this extension

src/services/service-worker.ts
pwa-starter service worker was not being found because I cannot spell.
=> fix(): service worker path finder was spelled wrong

src/services/service-worker.ts
fixes https://github.com/pwa-builder/PWABuilder/issues/2426
Also fixes an issue where the service worker could be pulled from node_modules and an issue where the service worker would not be added to your index.html if you already had one.
=> fix(): fixes https://github.com/pwa-builder/PWABuilder/issues/2426

src/services/manifest/manifest-content.ts
Fixes https://github.com/pwa-builder/PWABuilder/issues/2425
=> fix(): fixes https://github.com/pwa-builder/PWABuilder/issues/2425

package-lock.json, src/extension.ts, src/services/service-worker.ts, tsconfig.json
Fixes https://github.com/pwa-builder/PWABuilder/issues/2454. The advanced service worker option is now the one you would use to cover the use case in this issue.
=> Service worker mod

src/services/web-publish.ts
fixes https://github.com/pwa-builder/PWABuilder/issues/2510
=> userexperience(): more detailed walkthrough

src/services/manifest/manifest-content.ts
fixes https://github.com/pwa-builder/PWABuilder/issues/2508
=> fix(): manifest info links are correct

package-lock.json, src/library/file-utils.ts, src/services/manifest/manifest-service.ts, src/services/service-worker.ts, src/services/validation/sw-view.ts, src/services/validation/validation-view.ts
fixes https://github.com/pwa-builder/PWABuilder/issues/2513
=> fix(): paths are now always correct

src/library/package-utils.ts, src/services/manifest/manifest-service.ts, src/services/package/package-android-app.ts, src/services/package/package-app.ts, src/services/service-worker.ts, src/services/validation/sw-view.ts, src/services/validation/validation-view.ts, src/services/web-publish.ts
- Better error messages
- Fixed potential undefined situations
- Fixed bug with azure flow
=> fix(): better error messages + bug fixes

package-lock.json, package.json
Generate Icons hadn't been added to package.json and wasn't displaying in command filter in Code.
Added the command to activationEvents and commands in `package.json`.
=> Added Generate Icons command

package.json
Just needed to add the entry for Typescript files.
=> fixes https://github.com/pwa-builder/PWABuilder/issues/2557

.github/workflows/main.yml, CHANGELOG.md, package.json, src/services/new-pwa-starter.ts, src/services/package/package-app.ts, src/services/service-worker.ts, src/services/usage-analytics.ts, src/views/icons-view.ts, src/views/manifest-view.ts
- We now track usage of all our existing commands
- Updated the build to handle this new code
=> feat(): better usage tracking analytics

src/services/new-pwa-starter.ts, src/test/suite/extension.test.ts
Fixes https://github.com/pwa-builder/PWABuilder/issues/2635
=> Added a directory selection prompt for New PWA Starter Command

.vscode/launch.json, package-lock.json, package.json
- Bundles the extension with esbuild
- Adds types for ShellJS
=> fixes https://github.com/pwa-builder/PWABuilder/issues/2624

package.json
Fixes https://github.com/pwa-builder/PWABuilder/issues/2781
=> Icon update

src/services/web-publish.ts, src/utils.ts
Fixes https://github.com/pwa-builder/PWABuilder/issues/2949
We now validate URLs, to the best extent possible, using a regex that I found is commonly used. Note however, that URL validation is an not an exact science.
=> Validate url

package.json, src/library/package-utils.ts, src/questions.ts, src/services/package/meta-interfaces.ts, src/services/package/package-app.ts
Packaging for Meta Quest devices (:
Fixes https://github.com/pwa-builder/PWABuilder/issues/3009
=> feat(): Can package for Meta Quest devices
